import master_game.controllers.graphql_controller
import master_game.controllers.authification_controller
import master_game.controllers.character_controller
import master_game.controllers.first_page_controller
import master_game.controllers.game_controller
